const router = require('express').Router();
const { protect } = require('../middleware/authMiddleware');
const upload = require('../middleware/discoveryUpload');
const controller = require('../controllers/discoveryController');
const { uploadLimiter } = require('../middleware/rateLimits');
const { uploadWorkGuard } = require('../middleware/uploadWorkGuard');
router.use(protect);
router.get('/', controller.listDiscoveries);
router.post('/', uploadLimiter, uploadWorkGuard, upload, controller.createDiscovery);
router.get('/:id/photo', controller.getDiscoveryPhoto);
router.put('/:id', uploadLimiter, uploadWorkGuard, upload, controller.updateDiscovery);
router.delete('/:id', controller.deleteDiscovery);
module.exports = router;
